#!/bin/bash

run=false
if [[ $1 == -r || $1 == --run ]]; then
    run=true
    shift
fi

filename=$1

[[ -z $filename ]] && read -p "script title: " -r filename
[[ $filename == *.gd ]] || filename="$filename".gd

cat >"$filename" <<-EOF
extends Node


func _init() -> void:
    pass


func _ready() -> void:
    queue_free()


# vim:et:ts=4:sts=4:sw=4
EOF

ret=$?
(( ret > 0 )) && exit $ret

${EDITOR:-/bin/vim} -- "$filename"
$run && ./run.gd "$filename"

# vim:et:ts=4:sts=4:sw=4
